# Generated by Django 2.0.13 on 2019-06-17 22:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default=0, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
