# Generated by Django 2.0.13 on 2019-06-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
